function info = initializeInfo()
        % Crear un arreglo vacío de personas.
        info = struct(...
            'id', {}, ...
            'entrada', {}, ...
            'salida', {}, ...
            'rectangulo', {}, ...
            'angulo', {}, ...
            'centroide', {}, ...
            'totalVisibleCount', {});
end