function [info, tracks, nextId] = createNewTracks(info, tracks, ...
        unassignedDetections, centroids, bboxes, nextId)
    
    centroids = centroids(unassignedDetections, :);
    bboxes = bboxes(unassignedDetections, :);

    for i = 1:size(centroids, 1)

        centroid = centroids(i,:);
        bbox = bboxes(i, :);

        % Crear objeto de Filtro de Kalman.
        kalmanFilter = configureKalmanFilter('ConstantVelocity', ...
            centroid, [200, 50], [100, 25], 100);

        % Crear nueva estructura de track.
        newTrack = struct(...
            'id', nextId, ...
            'bbox', bbox, ...
            'kalmanFilter', kalmanFilter, ...
            'age', 1, ...
            'totalVisibleCount', 1, ...
            'consecutiveInvisibleCount', 0);

        % Crear nueva estructura de persona.
        newInfo = struct(...
            'id', nextId, ...
            'entrada', datetime('now'), ...
            'salida', 0, ...
            'rectangulo', bbox(3:4), ...
            'angulo', 0, ...
            'centroide', centroid, ...
            'totalVisibleCount', 1);
        
        % Añadir a los arreglos de track e info.
        tracks(end + 1) = newTrack;
        info(end + 1) = newInfo;

        % Asignar la siguiente Id.
        nextId = nextId + 1;
    end
end